# This is a basic workflow that is manually triggered

name: Sast_Code_Scan--Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      URL_Issue:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'URL of Issue-Comment where is the script to scan'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sast-code-scan"
  sast-code-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.MY_SECRET_T0K3N }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Configure Python Env
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Print Path
      run: |
        pwd
        ls -lAtrh

    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute the script with token
      run: |
        python sast-code-scan.py ${{ inputs.URL_Issue }} $TOKEN
